services:
  ccbb-frontend:
    build:
      context: ./Frontend/ccbb-frontend
    depends_on:
      - ccbb-backend
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./Frontend/ccbb-frontend/
          target: /app
        - action: rebuild
          path: ./Frontend/ccbb-frontend/package.json

  ccbb-backend:
    build:
      context: ./Backend
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./Backend/ccbb_backend
          target: /app/ccbb_backend
        - action: rebuild
          path: ./Backend/requirements.txt
        - action: rebuild
          path: ./Backend/ccbb_backend/models.py
    volumes:
      - db-data:/app/data

volumes:
  db-data: